### PR TITLE
Add `alpine pause` and `alpine resume`

### PR DESCRIPTION
**Pull request by maxzinkus**
Support for pausing/unpausing instances using `SIGSTOP` and `SIGCONT`

* `alpine pause` and `alpine resume` commands
* show `Paused` in `alpine list`
* logic in `start`, `stop`, and `ssh` to keep things coherent

### CODE REVIEW

**Comment by maxzinkus** [comment]
Note that a paused VM will still take system resources, particularly, RAM.

**Comment by idroz** [comment]
I've been looking into this recently, particularly at VM suspension, but haven't considered `SIGSTOP` approach.

My current thinking was to hook up to the QMP socket (socket file is created for each running VM inside VM's subdirectory) and issue a `Stop` command, but not sure if it's an overkill, particularly if it won't free up resources (need to investigate).

I'm not familiar enough with `SIGSTOP`. What would be the main use case here and are there any downsides?

**Comment by maxzinkus** [comment]
`SIGSTOP` suspends a process, stopping it from being scheduled onto the CPU. It keeps around all the resources (process table entry, VMM, etc) for immediate resumption with `SIGCONT`.

The guest will resume thinking no time has passed, so this could contribute to clock desync. We could throw a `machineConfig.Exec("hwclock -s")` in the `resume` flow?

**Comment by idroz** [comment]
Cool - I think `resume` should have `machineConfig.Exec("hwclock -s")`, similar to `alpine start`. Would make it more seamless for the user

**Comment by maxzinkus** [comment]
Notably, (and I think this is kind of nice), it does not release the port bindings for hostfwd. That means we won't have weird bind crashes upon resume.

**Comment by idroz** [comment]
Agreed - was playing around with the PR and spotted that - it is quite nice I think.

**Comment by maxzinkus** [comment]
Added the clock-resync, again with the assumption that the system time is the user's responsibility

**Comment by idroz** [comment]
Nice - could you also run `go run document.go` inside `/docs` directory and commit changes into this PR - it'll update the main docs with the new CLI commands.

**Comment by maxzinkus** [comment]
Done! And thanks, I can do that in the future for PRs now that I know how :)

**Review by idroz — APPROVED** [review]

**Pull request merged**
